name: Deploy to Raspberry Pi

on:
  # workflow_dispatch:   # manual button, removed as this is public repo
  push:
    branches: [main]   # optional auto deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/raspberry/git-repo/self-host-script-job-deployment
          git fetch origin
          git reset --hard origin/main

      - name: Rebuild image via Dockge
        run: |
          cd /home/raspberry/git-repo/self-host-script-job-deployment
          docker compose build --no-cache my-job